# Generated by Django 3.1.1 on 2020-09-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '장고 공부', 'verbose_name_plural': '장고 공부'},
        ),
    ]
